name: "Publish to Valar"
on:
  push:
    branches:    
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Frontend
      uses: valar/action@v2
      with:
        token: ${{ secrets.VALAR_TOKEN }}
        workdir: ./display
    - name: Publish Backend
      uses: valar/action@v2
      with:
        token: ${{ secrets.VALAR_TOKEN }}
        workdir: ./server
